trigger: none

pool:
  vmImage: ubuntu-22.04

resources:
  repositories:
    - repository: templates
      type: git
      name: TECH-SW-PE/PE.PipelineTemplates
      ref: refs/heads/main

steps:
  - template: templates/minver.yml@templates

  - task: UseDotNet@2
    displayName: "Use .NET 10"
    inputs:
      packageType: "sdk"
      version: "10.x"

  - task: DotNetCoreCLI@2
    displayName: "Restore Packages"
    inputs:
      command: "restore"
      projects: "src/Messaging.Kafka/Messaging.Kafka.csproj"
      feedsToUse: "select"
      verbosityRestore: Normal

  - task: DotNetCoreCLI@2
    displayName: "Build Packages"
    inputs:
      command: "build"
      projects: "src/Messaging.Kafka/Messaging.Kafka.csproj"
      arguments: "-c Release"

  - task: DotNetCoreCLI@2
    displayName: "Pack Packages"
    inputs:
      command: "pack"
      packagesToPack: "src/Messaging.Kafka/Messaging.Kafka.csproj"
      nobuild: true
      includesymbols: true
      includesource: true
      versioningScheme: "off"
      buildProperties: "PackageVersion=$(minver.version)"
      verbosityPack: Normal

  - task: PublishBuildArtifacts@1
    displayName: "Publish Pipeline Artifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "Messaging.Kafka"
      publishLocation: "Container"

  - task: NuGetCommand@2
    displayName: "Publish NuGet"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "a9ccef66-b9c3-42ca-b550-1b34b08e0be4"
