<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ClearingOrchestrator.Service-cf6b929c-f0fc-40a5-98ec-efbd0a5e07c8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>
</Project>
