apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-config
  namespace: default
data:
  connect-distributed.properties: |
    group.id=debezium-outbox-connect-cluster

    bootstrap.servers=${env:KAFKA_BOOTSTRAP_SERVERS}

    config.storage.topic=debezium-connect-configs
    offset.storage.topic=debezium-connect-offsets
    status.storage.topic=debezium-connect-statuses
    config.storage.replication.factor=1
    offset.storage.replication.factor=1
    status.storage.replication.factor=1
    offset.flush.interval.ms=10000

    key.converter=org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable=false
    value.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable=false
    rest.port=8083
    rest.advertised.host.name=${env:POD_IP}
    plugin.path=/kafka/connect
