import os
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, substring
from pyspark.sql.protobuf.functions import from_protobuf

# --- Configuration ---
KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP", "kafka:9092")
S3_ENDPOINT = os.getenv("S3_ENDPOINT", "http://minio:9000")
S3_ACCESS_KEY = os.getenv("S3_ACCESS_KEY", "minioadmin")
S3_SECRET_KEY = os.getenv("S3_SECRET_KEY", "minioadmin")
JDBC_URL = os.getenv("JDBC_URL", "jdbc:postgresql://postgres:5432/iceberg_catalog")
JDBC_USER = os.getenv("JDBC_USER", "postgres")
JDBC_PASSWORD = os.getenv("JDBC_PASSWORD", "postgres")

# Descriptor file generated by protoc in Dockerfile
PROTO_DESCRIPTOR_PATH = "/app/journal.desc"
PROTO_MESSAGE_NAME = "ledger.public.journal_entries.Value"

# --- Spark Session ---
spark = SparkSession.builder \
    .appName("LedgerToIcebergIngestion") \
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
    .config("spark.sql.catalog.clearing_lake", "org.apache.iceberg.spark.SparkCatalog") \
    .config("spark.sql.catalog.clearing_lake.type", "jdbc") \
    .config("spark.sql.catalog.clearing_lake.uri", JDBC_URL) \
    .config("spark.sql.catalog.clearing_lake.jdbc.user", JDBC_USER) \
    .config("spark.sql.catalog.clearing_lake.jdbc.password", JDBC_PASSWORD) \
    .config("spark.sql.catalog.clearing_lake.warehouse", "s3a://clearing-lake/warehouse") \
    .config("spark.sql.catalog.clearing_lake.io-impl", "org.apache.iceberg.aws.s3.S3FileIO") \
    .config("spark.sql.catalog.clearing_lake.s3.endpoint", S3_ENDPOINT) \
    .config("spark.sql.catalog.clearing_lake.s3.path-style-access", "true") \
    .config("spark.sql.catalog.clearing_lake.s3.access-key-id", S3_ACCESS_KEY) \
    .config("spark.sql.catalog.clearing_lake.s3.secret-access-key", S3_SECRET_KEY) \
    .config("spark.hadoop.fs.s3a.endpoint", S3_ENDPOINT) \
    .config("spark.hadoop.fs.s3a.access.key", S3_ACCESS_KEY) \
    .config("spark.hadoop.fs.s3a.secret.key", S3_SECRET_KEY) \
    .config("spark.hadoop.fs.s3a.path.style.access", "true") \
    .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
    .getOrCreate()

# --- 1. Ensure Table Exists ---
spark.sql("""
    CREATE TABLE IF NOT EXISTS clearing_lake.captured_transactions (
        entry_id            BIGINT,
        transaction_id      STRING,
        network             STRING,
        event_timestamp     TIMESTAMP,
        merchant_id         STRING,
        arn                 STRING,
        gross_amount        DECIMAL(18,2),
        currency            STRING,
        installment_number  INT,
        installment_total   INT,
        clearing_date       DATE,
        event_type          STRING
    )
    USING iceberg
    PARTITIONED BY (network, clearing_date)
""")

# --- 2. Read from Kafka ---
df_kafka = spark.readStream \
    .format("kafka") \
    .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP) \
    .option("subscribe", "ledger.journal.events") \
    .option("startingOffsets", "earliest") \
    .load()

# --- 3. Slice Confluent Magic Header (5 bytes) and Deserialize ---
# Confluent Encoding: 0x00 (Magic Byte) + Schema ID (4 bytes) + Protobuf Payload
df_proto = df_kafka.select(
    from_protobuf(
        expr("substring(value, 7, length(value))"), # Strip the first 6 bytes (0x00 + 4-byte schema ID + 1-byte version/flags)
        PROTO_MESSAGE_NAME, 
        PROTO_DESCRIPTOR_PATH
    ).alias("msg")
)

from pyspark.sql.functions import udf
from pyspark.sql.types import DecimalType
import decimal

@udf(returnType=DecimalType(18, 2))
def decode_confluent_decimal(b, scale):
    if b is None:
        return None
    unscaled = int.from_bytes(b, byteorder='big', signed=True)
    return decimal.Decimal(unscaled) / (decimal.Decimal(10) ** scale)

# --- 4. Flatten and Filter ---
df_final = df_proto.select(
    col("msg.entry_id"),
    col("msg.transaction_id"),
    col("msg.network"),
    col("msg.event_timestamp").cast("timestamp").alias("event_timestamp"),
    col("msg.merchant_id"),
    col("msg.arn"),
    decode_confluent_decimal(col("msg.gross_amount.value"), col("msg.gross_amount.scale")).alias("gross_amount"),
    col("msg.currency"),
    col("msg.installment_number"),
    col("msg.installment_total"),
    expr("date_add('1970-01-01', msg.clearing_date)").alias("clearing_date"),
    col("msg.event_type")
).filter(col("msg.event_type") == "capture")

# --- 5. Write to Iceberg ---
query = df_final.writeStream \
    .format("iceberg") \
    .outputMode("append") \
    .trigger(processingTime="1 minute") \
    .option("path", "clearing_lake.captured_transactions") \
    .option("checkpointLocation", "s3a://clearing-lake/checkpoints/ingestion") \
    .start()

query.awaitTermination()
