import os
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, substring
from pyspark.sql.protobuf.functions import from_protobuf

# --- Configuration ---
KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP", "kafka:9092")
S3_ENDPOINT = os.getenv("S3_ENDPOINT", "http://minio:9000")
S3_ACCESS_KEY = os.getenv("S3_ACCESS_KEY", "minioadmin")
S3_SECRET_KEY = os.getenv("S3_SECRET_KEY", "minioadmin")
JDBC_URL = os.getenv("JDBC_URL", "jdbc:postgresql://postgres:5432/iceberg_catalog")
JDBC_USER = os.getenv("JDBC_USER", "postgres")
JDBC_PASSWORD = os.getenv("JDBC_PASSWORD", "postgres")

# Descriptor file generated by protoc in Dockerfile
PROTO_DESCRIPTOR_PATH = "/app/journal.desc"
PROTO_MESSAGE_NAME = "ledger.public.journal_entries.Value"

# --- Spark Session ---
spark = SparkSession.builder \
    .appName("LedgerToIcebergIngestion") \
    .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
    .config("spark.sql.catalog.clearing_lake", "org.apache.iceberg.spark.SparkCatalog") \
    .config("spark.sql.catalog.clearing_lake.type", "jdbc") \
    .config("spark.sql.catalog.clearing_lake.uri", JDBC_URL) \
    .config("spark.sql.catalog.clearing_lake.jdbc.user", JDBC_USER) \
    .config("spark.sql.catalog.clearing_lake.jdbc.password", JDBC_PASSWORD) \
    .config("spark.sql.catalog.clearing_lake.jdbc.schema-version", "V1") \
    .config("spark.sql.catalog.clearing_lake.warehouse", "s3a://clearing-lake/warehouse") \
    .config("spark.sql.catalog.clearing_lake.io-impl", "org.apache.iceberg.aws.s3.S3FileIO") \
    .config("spark.sql.catalog.clearing_lake.s3.endpoint", S3_ENDPOINT) \
    .config("spark.sql.catalog.clearing_lake.s3.path-style-access", "true") \
    .config("spark.sql.catalog.clearing_lake.s3.access-key-id", S3_ACCESS_KEY) \
    .config("spark.sql.catalog.clearing_lake.s3.secret-access-key", S3_SECRET_KEY) \
    .config("spark.hadoop.fs.s3a.endpoint", S3_ENDPOINT) \
    .config("spark.hadoop.fs.s3a.access.key", S3_ACCESS_KEY) \
    .config("spark.hadoop.fs.s3a.secret.key", S3_SECRET_KEY) \
    .config("spark.hadoop.fs.s3a.path.style.access", "true") \
    .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
    .getOrCreate()

# --- 1. Ensure Table Exists ---
# --- Pre-Create the Iceberg Table ---
# This ensures the table exists with the correct partitioning ('network' and 'clearing_date')
# before the streaming job starts. Partitioning by clearing_date allows for fast batch deletions/retries.
spark.sql("""
    CREATE TABLE IF NOT EXISTS clearing_lake.captured_transactions (
        entry_id            BIGINT,
        transaction_id      STRING,
        network             STRING,
        event_timestamp     TIMESTAMP,
        merchant_id         STRING,
        arn                 STRING,
        gross_amount        DECIMAL(18,2),
        currency            STRING,
        installment_number  INT,
        installment_total   INT,
        clearing_date       DATE,
        event_type          STRING
    )
    USING iceberg
    PARTITIONED BY (network, clearing_date)
""")

# --- 2. Read from Kafka ---
df_kafka = spark.readStream \
    .format("kafka") \
    .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP) \
    .option("subscribe", "ledger.journal.events") \
    .option("startingOffsets", "earliest") \
    .option("failOnDataLoss", "false") \
    .option("kafka.metadata.max.age.ms", "1000") \
    .option("kafka.consumer.config.retry.backoff.ms", "500") \
    .load()

# --- Deserialize Protobuf with Confluent Header Skip ---
# Confluent Wire Format: 0x00 (1) + Schema ID (4) + Message Index (1) = 6 bytes total.
# Spark's substring is 1-indexed, so starting at position 7 effectively removes the first 6 bytes.
# This allows 'from_protobuf' to read the clean Protobuf payload.
df_proto = df_kafka.select(
    from_protobuf(
        expr("substring(value, 7, length(value))"), 
        PROTO_MESSAGE_NAME, 
        PROTO_DESCRIPTOR_PATH
    ).alias("msg")
)

from pyspark.sql.functions import udf
from pyspark.sql.types import DecimalType
import decimal

@udf(returnType=DecimalType(18, 2))
def decode_confluent_decimal(b, scale):
    if b is None:
        return None
    unscaled = int.from_bytes(b, byteorder='big', signed=True)
    return decimal.Decimal(unscaled) / (decimal.Decimal(10) ** scale)

# --- 4. Flatten and Filter ---
df_final = df_proto.select(
    col("msg.entry_id"),
    col("msg.transaction_id"),
    col("msg.network"),
    col("msg.event_timestamp").cast("timestamp").alias("event_timestamp"),
    col("msg.merchant_id"),
    col("msg.arn"),
    decode_confluent_decimal(col("msg.gross_amount.value"), col("msg.gross_amount.scale")).alias("gross_amount"),
    col("msg.currency"),
    col("msg.installment_number"),
    col("msg.installment_total"),
    col("msg.event_timestamp").cast("date").alias("clearing_date"),
    col("msg.event_type")
).filter(col("msg.event_type") == "capture")

# --- 5. Write to Iceberg ---
# --- 5. Write to Iceberg ---
def merge_to_iceberg(batch_df, batch_id):
    batch_df.createOrReplaceTempView("updates")
    batch_df._jdf.sparkSession().sql("""
        MERGE INTO clearing_lake.captured_transactions t
        USING updates s
        ON t.entry_id = s.entry_id
        WHEN MATCHED THEN UPDATE SET 
            t.event_type = s.event_type
        WHEN NOT MATCHED THEN INSERT *
    """)

query = df_final.writeStream \
    .foreachBatch(merge_to_iceberg) \
    .trigger(processingTime="1 minute") \
    .option("checkpointLocation", "s3a://clearing-lake/checkpoints/ingestion") \
    .start()

query.awaitTermination()
