<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ImplicitUsings>enable</ImplicitUsings>  
  </PropertyGroup>
  
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>True</IncludeSymbols>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Product>OI.Messaging.Kafka</Product>
    <Title>OI.Messaging.Kafka</Title>
    <Owners>OI Engineering</Owners>
    <Authors>OI Engineering</Authors>
    <Copyright>Copyright © Ocean Infinity 2026</Copyright>
    <Description>Abstracts common kafka features</Description>
    <Version>0.0.1</Version>
    <AssemblyVersion>0.0.1</AssemblyVersion>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <PackageId>OI.Messaging.Kafka</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.*" />

    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.*" />

    <PackageReference Include="Confluent.Kafka" Version="2.*" />
    <PackageReference Include="Google.Protobuf" Version="3.29.*" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Protobuf" Version="2.13.*" />
    <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="2.13.*" />
    <PackageReference Include="Polly" Version="8.6.*" />
    <PackageReference Include="Polly.Extensions" Version="8.6.*" />
    <PackageReference Include="protobuf-net.Reflection" Version="3.2.52" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(OutputPath)\*.dll" Pack="true" PackagePath="lib\$(TargetFramework)" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>OI.Messaging.Kafka.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Content Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>


</Project>
